/*
 * !++
 * QDS - Quick Data Signalling Library
 * !-
 * Copyright (C) 2002 - 2021 Devexperts LLC
 * !-
 * This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
 * If a copy of the MPL was not distributed with this file, You can obtain one at
 * http://mozilla.org/MPL/2.0/.
 * !__
 */
package com.dxfeed.event.misc.impl;

import com.devexperts.io.Marshalled;
import com.devexperts.qd.DataRecord;
import com.devexperts.qd.ng.RecordCursor;
import com.devexperts.qd.ng.RecordMapping;
import com.devexperts.qd.util.MappingUtil;

public class MessageMapping extends RecordMapping {
// BEGIN: CODE AUTOMATICALLY GENERATED: DO NOT MODIFY. IT IS REGENERATED BY com.dxfeed.api.codegen.ImplCodeGen
    private final int oMessage;

    public MessageMapping(DataRecord record) {
        super(record);
        oMessage = MappingUtil.findObjField(record, "Message", true);
    }

    public Marshalled<?> getMessage(RecordCursor cursor) {
        return MappingUtil.getMarshalled(getObj(cursor, oMessage));
    }

    public void setMessage(RecordCursor cursor, Marshalled<?> message) {
        setObj(cursor, oMessage, message);
    }
// END: CODE AUTOMATICALLY GENERATED
}
