# Universe master configuration sample
{
    # Spaces and products are identified by their name. This identity is shared among all spaces and products.
    # Characters allowed in these identifiers shall be carefully clarified, as this name may be part of many contexts
    # (config files, connection specs, communication protocols, file names, etc).

    spaces: {
        # Every space is a separate self-sustained subset of data managed by a separate data structures.
        sample: {
            filter = "*"                           // Space definition filter. Primary aspect. Anything by default.
            contracts = [ticker, stream, history]  // List of supported contracts. All by default.
            active = true                          // Active status. Inactive spaces are placeholders. True by default.
            enableWildcards = true                 // Enable wildcard subscription. True by default.
            eventTimeSequence = false              // Enable processing of event time and sequence. False by default.
            storeEverything = false                // Store everything mode. False by default.
            storeEverythingFilter = "*"            // Store everything filter. Anything by default.
            // TODO: stripe = byhash4 (?????)
            // TODO: transportChannel = shareSpace:US_INDICES | exclusive_space:NTV | exclusive_stripe:OPRA (???)
            // exclusive_stripe = socket-per-stripe
        }
        
        archive: {}
        realtime: {}
    }

    products: {
        # Every product is a list of channels (data access definitions) processed in the specified order.
        simple: [{
            base = sample                          // Name of base space or product. Required field. No default value.
            filter = "*"                           // Product definition filter. Primary aspect. Anything by default.
            contracts = [ticker, stream, history]  // List of supported contracts. All by default.
            aggregationPeriod = 0                  // Data aggregation period. Zero (no aggregation) by default.
            allowWildcards = false                 // Allow wildcard subscription. False by default.
        }]

        archive-ap1s: [{base = archive, aggregationPeriod = 1s}]
        realtime-ap1s: [{base = realtime, aggregationPeriod = 1s}]
    }

    # Lists of spaces allow local overrides of related space properties.
    # [] (empty list) indicates that no local override is applied and spaces shall keep their original properties.
    # ["*"] matches all spaces and turns on related property for every space.
    # ["!*"] matches no spaces and turns off related property for every space.
    activeSpaces: []
    enableWildcardsSpaces: []
    eventTimeSequenceSpaces: []
    storeEverythingSpaces: []
}
